//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurs_pr
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupServices
    {
        public GroupServices()
        {
            this.Positions = new HashSet<Positions>();
            this.Service = new HashSet<Service>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Positions> Positions { get; set; }
        public virtual ICollection<Service> Service { get; set; }

        public override string ToString()
        {
            return name;
        }
    }
}
