//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurs_pr
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int Id { get; set; }
        public int role { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual Role Role1 { get; set; }
    }
}
